### ISSUE TITLE
401 on build

### ISSUE THREAD

**Issue by cmcculloh-kr** [ghostdevv/sveltekit-basic-auth#2]
When I clone the repo and run `npm build` I get this:

<img width="923" alt="image" src="https://user-images.githubusercontent.com/8006971/164112781-48d69a27-4002-40a3-9ea3-1abaa67d7527.png">

**Comment by ghostdevv** [comment]
Hi, I added this line to the config which will fix that issue:

```js
prerender: {
    enabled: false,
},
```

You can see that here: https://github.com/ghostdevv/sveltekit-basic-auth/blob/main/svelte.config.js#L14
